/*
 * Single-file launcher for a frozen Python application.
 *
 * Links statically against libpython and carries every Python module
 * (application, dependencies, standard library) as marshalled code inside
 * the executable. Modules are handed to CPython through its own frozen-module
 * table (PyImport_FrozenModules), so imports are served from memory by the
 * interpreter's built-in FrozenImporter: nothing is unpacked to disk and no
 * custom importer is involved.
 *
 * frozen_index.h and payload.bin are generated by build.py.
 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include "frozen_index.h" /* APP_ENTRY_COUNT, app_index[], RUN_COMMAND */

static const unsigned char app_payload[] = {
#embed "payload.bin"
};

static struct _frozen frozen_table[APP_ENTRY_COUNT + 1];

static int
fail(PyConfig *config, PyStatus status)
{
    PyConfig_Clear(config);
    if (PyStatus_IsExit(status)) {
        return status.exitcode;
    }
    Py_ExitStatusException(status);
    return 1; /* not reached */
}

int
main(int argc, char **argv)
{
    for (int i = 0; i < APP_ENTRY_COUNT; i++) {
        frozen_table[i].name = app_index[i].name;
        frozen_table[i].code = app_payload + app_index[i].offset;
        frozen_table[i].size = (int)app_index[i].size;
        frozen_table[i].is_package = app_index[i].is_package;
    }
    /* frozen_table[APP_ENTRY_COUNT] stays zeroed: the terminator. */
    PyImport_FrozenModules = frozen_table;

    /* Isolated mode ignores PYTHON* environment variables, but still honour
       the user's locale (LC_ALL/LANG) so stdout gets the right encoding. */
    PyPreConfig preconfig;
    PyPreConfig_InitIsolatedConfig(&preconfig);
    preconfig.configure_locale = 1;
    PyStatus status = Py_PreInitializeFromBytesArgs(&preconfig, argc, argv);
    if (PyStatus_Exception(status)) {
        Py_ExitStatusException(status);
    }

    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);

    config.site_import = 0;             /* nothing on disk to scan */
    config.write_bytecode = 0;          /* never write __pycache__ */
    config.optimization_level = 1;      /* matches how the payload was compiled */
    config.module_search_paths_set = 1; /* start with an empty sys.path */
    config.install_signal_handlers = 1; /* Ctrl-C -> KeyboardInterrupt */

    status = PyConfig_SetBytesArgv(&config, argc, argv);
    if (PyStatus_Exception(status)) {
        return fail(&config, status);
    }
    status = PyConfig_SetString(&config, &config.run_command, RUN_COMMAND);
    if (PyStatus_Exception(status)) {
        return fail(&config, status);
    }
    status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status)) {
        return fail(&config, status);
    }
    PyConfig_Clear(&config);

    return Py_RunMain();
}
